name: build
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
    branches:
      - master
      - main

jobs:
  build_natives:
    permissions:
      contents: write
    name: Build deploy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          java-package: jdk
          cache: 'maven'

      - name: Build, test, package, install
        run: mvn clean install

      - name: Prepare GPG sign
        env:
          PRIVATE_KEY_BASE64: ${{ secrets.PRIVATE_KEY_BASE64 }}
        run: |
          gpg --version
          gpg --batch --import <(echo "$PRIVATE_KEY_BASE64" | base64 --decode)
      - name: Deploy version
        env:
          MVN_SETTINGS: ${{ secrets.MVN_SETTINGS }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$MVN_SETTINGS" | base64 --decode > /tmp/settings.xml
          mvn --settings /tmp/settings.xml --batch-mode --no-transfer-progress clean deploy -P release

      - name: Deploy Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "connect-retryable-${{github.ref_name}}"
          generate_release_notes: true
          files: |
            ./target/*.jar
            ./target/*.asc
            ./target/*.md5
            ./target/*.sha1
